{{- range .Values.repositories }}
apiVersion: 1
kind: Secret
metadata:
  name: {{ .name }}
  namespace: argocd
  annotations:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: {{ .url }}
  insecure: "{{ .repoConfig.insecure }}"
  enableLfs: "{{.repoConfig.enableLfs }}"
---
{{- end }}
